/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logina;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import Logina.admin_page;
/**
 *
 * @author 101847
 */
public class admin_1 extends javax.swing.JFrame {

    /**
     * Creates new form admin_1
     */
    public admin_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnPasswordadm = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jbtnUsernameadm = new javax.swing.JTextField();
        jbtnLoginadm = new javax.swing.JButton();
        jbtnResetadm = new javax.swing.JButton();
        jbtnExitadm = new javax.swing.JButton();
        jbtnRegistation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(28, 578));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Admin Login");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(919, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Username");

        jbtnPasswordadm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Password");

        jbtnUsernameadm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jbtnUsernameadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsernameadmActionPerformed(evt);
            }
        });

        jbtnLoginadm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnLoginadm.setText("Login");
        jbtnLoginadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginadmActionPerformed(evt);
            }
        });

        jbtnResetadm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnResetadm.setText("Reset");
        jbtnResetadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetadmActionPerformed(evt);
            }
        });

        jbtnExitadm.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnExitadm.setText("Exit");
        jbtnExitadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitadmActionPerformed(evt);
            }
        });

        jbtnRegistation.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnRegistation.setText("Registration");
        jbtnRegistation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(282, 282, 282)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnUsernameadm, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jbtnPasswordadm)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jbtnLoginadm)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnResetadm)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRegistation)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnExitadm)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtnUsernameadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnPasswordadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLoginadm)
                    .addComponent(jbtnResetadm)
                    .addComponent(jbtnExitadm)
                    .addComponent(jbtnRegistation))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitadmActionPerformed
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExitadmActionPerformed

    private void jbtnResetadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetadmActionPerformed
        jbtnUsernameadm.setText(null);
        jbtnPasswordadm.setText(null);
    }//GEN-LAST:event_jbtnResetadmActionPerformed

    private void jbtnUsernameadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsernameadmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnUsernameadmActionPerformed

    private void jbtnLoginadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginadmActionPerformed
        {
        String Password = jbtnPasswordadm.getText();
        String Username = jbtnUsernameadm.getText();
        
        if (Password.contains("8") && (Username.contains("admin")))
        {
            jbtnUsernameadm.setText(null);
            jbtnPasswordadm.setText(null);
            systemExit();
            
            admin_page Info = new admin_page();
            Info.setVisible(true);
        }
        
            else
        {
            JOptionPane.showMessageDialog(null,"Invail login Details", "login Error",JOptionPane.ERROR_MESSAGE);
                jbtnPasswordadm.setText(null);
                jbtnUsernameadm.setText(null);
        }
    }                                         

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLoginadmActionPerformed

    private void jbtnRegistationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistationActionPerformed
         registe_new Info = new registe_new();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnRegistationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnExitadm;
    private javax.swing.JButton jbtnLoginadm;
    private javax.swing.JPasswordField jbtnPasswordadm;
    private javax.swing.JButton jbtnRegistation;
    private javax.swing.JButton jbtnResetadm;
    private javax.swing.JTextField jbtnUsernameadm;
    // End of variables declaration//GEN-END:variables


    private void systemExit()
    {
        WindowEvent winClosing = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
    }

}
